// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Fnq9BE13mNLprbBj03_syNJAlbZFsws',
    appId: '1:841246552092:web:a0dc6c46f01e7e3c092fd9',
    messagingSenderId: '841246552092',
    projectId: 'flutter-todo-list-project',
    authDomain: 'flutter-todo-list-project.firebaseapp.com',
    storageBucket: 'flutter-todo-list-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmdjLP-jvN11ovCYJfY8FyDiY6KUR_Ago',
    appId: '1:841246552092:android:1434f609fe22be1b092fd9',
    messagingSenderId: '841246552092',
    projectId: 'flutter-todo-list-project',
    storageBucket: 'flutter-todo-list-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFBvvmmw_gzN3SVZYvNKyN_NomoK60tTk',
    appId: '1:841246552092:ios:9a944e8843ee3bb2092fd9',
    messagingSenderId: '841246552092',
    projectId: 'flutter-todo-list-project',
    storageBucket: 'flutter-todo-list-project.appspot.com',
    iosClientId: '841246552092-ti6saq9t2h3s6mlfa5agusjpa6add6pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFBvvmmw_gzN3SVZYvNKyN_NomoK60tTk',
    appId: '1:841246552092:ios:2851298b63361ca4092fd9',
    messagingSenderId: '841246552092',
    projectId: 'flutter-todo-list-project',
    storageBucket: 'flutter-todo-list-project.appspot.com',
    iosClientId: '841246552092-8brtv2k70v7pv0t82mmh2o5kot5vnhta.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
